server:
  port: 8081
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: d08ed195-991e-4a85-aa5d-296929b34cfb
        username: nacos
        password: nacos