server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 正式环境
    #username: rw_cropser
    #password: XNRYwq9Wdz8^Tqde
    #url: jdbc:mysql://119.3.251.238:3306/db_crops_supervise?zeroDateTimeBehavior=CONVERT_TO_NULL
    # 开发环境
    url: jdbc:mysql://localhost:3306/db_crops_supervise?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
mybatis:
  type-aliases-package: com.example.crops_supervise_platform.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启mybatis驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志
